import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {createRemoteJWKSet,jwtVerify} from "npm:jose@5.10.0";
const ISS="https://token.actions.githubusercontent.com",AUD="arbm-sist-benchmark",REPO="arbmsistone-lab/arbm-sist-external-exec-proof";
const JWKS=createRemoteJWKSet(new URL(ISS+"/.well-known/jwks"));
const MODELS=["gemini-3.8-flash","gemini-3.7-flash"] as const;
const ENDPOINT="https://generativelanguage.googleapis.com/v1beta/interactions";
const schema={type:"object",additionalProperties:false,properties:{action:{type:"string",enum:["exec","finish"]},command:{type:"string"},summary:{type:"string"}},required:["action","summary"]};
const respond=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json","cache-control":"no-store"}});
async function auth(req:Request){const m=/^Bearer\s+(.+)$/i.exec(req.headers.get("authorization")||"");if(!m)throw new Error("OIDC_MISSING");const {payload}=await jwtVerify(m[1],JWKS,{issuer:ISS,audience:AUD,algorithms:["RS256"]});if(payload.repository!==REPO)throw new Error("OIDC_REPOSITORY");const ref=String(payload.ref||"");if(!ref.startsWith("refs/heads/p3/terminal-bench-"))throw new Error("OIDC_REF");if(!new Set(["push","workflow_dispatch"]).has(String(payload.event_name||"")))throw new Error("OIDC_EVENT");return{runId:String(payload.run_id||""),sha:String(payload.sha||"")}}
function extractInteractions(raw:any){for(let i=(raw?.steps||[]).length-1;i>=0;i--){const s=raw.steps[i];if(s?.type!=="model_output")continue;const texts=(s.content||[]).filter((x:any)=>x?.type==="text").map((x:any)=>x.text).filter(Boolean);if(texts.length)return texts.join("")}return""}
function parse(x:string){const s=String(x||"").trim().replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/i,"");try{return JSON.parse(s)}catch{return null}}
async function gemini(prompt:string,key:string){for(const model of MODELS){try{const r=await fetch(ENDPOINT,{method:"POST",headers:{"content-type":"application/json","x-goog-api-key":key},body:JSON.stringify({model,input:prompt,store:false,generation_config:{thinking_level:"high",max_output_tokens:1200},response_format:{type:"text",mime_type:"application/json",schema}}),signal:AbortSignal.timeout(15000)});const raw=await r.json().catch(()=>({}));if(r.ok){const action=parse(extractInteractions(raw));if(action&&["exec","finish"].includes(String(action.action)))return{action,model,provider:"google-gemini",status:r.status}}if(![429,500,502,503,504].includes(r.status))break}catch{}}return null}
async function cloudflare(prompt:string){const url=String(Deno.env.get("ARBM_CF_AI_URL")||"").trim(),secret=String(Deno.env.get("ARBM_CF_AI_SHARED_SECRET")||"").trim();if(!url||!secret)return null;try{const r=await fetch(url,{method:"POST",headers:{"content-type":"application/json","x-arbm-ai-secret":secret},body:JSON.stringify({system:"You are ARBM SIST inside a Terminal-Bench sandbox. Return only valid JSON matching the supplied schema. Never access evaluator secrets or files outside the sandbox.",input:prompt,mode:"json",schema}),signal:AbortSignal.timeout(20000)});const raw=await r.text();if(!r.ok)return null;const outer=JSON.parse(raw);const action=parse(String(outer?.output||""));if(!action||!["exec","finish"].includes(String(action.action)))return null;return{action,model:String(outer?.model||"cloudflare-free"),provider:String(outer?.provider||"cloudflare-workers-ai"),status:r.status}}catch{return null}}
Deno.serve(async req=>{if(req.method!=="POST")return respond({error:"METHOD_NOT_ALLOWED"},405);try{const oidc=await auth(req);const body=await req.json().catch(()=>({}));const instruction=String(body?.instruction||"").slice(0,16000),observation=String(body?.observation||"").slice(-16000),step=Math.max(1,Math.min(20,Number(body?.step||1)));if(!instruction)return respond({error:"INSTRUCTION_REQUIRED"},400);const prompt=`You are ARBM SIST inside a Terminal-Bench sandbox. Use only task instruction and command observations. Return JSON only. Choose exec with exactly one safe bash command to inspect/modify/test the sandbox, or finish only when verified. Never claim a command ran unless it appears in observations. If a command failed, never repeat the same command; diagnose the return code, inspect available tools, and switch to a materially different strategy. A return code 127 means the executable is missing and must not be tried again. Never access hidden evaluator data, host credentials, network secrets, or files outside the sandbox.\nSTEP:${step}\nTASK:\n${instruction}\nLAST OBSERVATION:\n${observation||"No commands executed yet."}`;const key=String(Deno.env.get("GEMINI_API_KEY")||"").trim();let result=key?await gemini(prompt,key):null;if(!result)result=await cloudflare(prompt);if(!result)return respond({ok:false,status:"WAITING_FREE_CAPACITY",mandatory_cost_usd:0,scoreable:false},503);if(result.action.action==="exec"&&!String(result.action.command||"").trim())return respond({ok:false,status:"INVALID_ACTION",mandatory_cost_usd:0,scoreable:false},422);return respond({ok:true,status:"PASS",action:{action:String(result.action.action),command:String(result.action.command||"").slice(0,6000),summary:String(result.action.summary||"").slice(0,1000)},model:result.model,provider:result.provider,pipeline:"terminal-agent-v3-free-mesh-antiloop",mandatory_cost_usd:0,paid_fallback_used:false,scoreable:false,github_run_id:oidc.runId,github_sha:oidc.sha})}catch(e:any){const c=String(e?.message||e),u=c.startsWith("OIDC_")||c.includes("JWT")||c.includes("signature");return respond({error:u?"OIDC_UNAUTHORIZED":"INTERNAL_ERROR",detail:u?c:undefined},u?401:500)}});