from capacity_excellence import chaos_floors,evidence_freshness
from resilience_capacity import certify_resilience
from mesh_capacity import _route_daily_units
ROLES=['capacity','resilience','billing','security','quota','routing','failover','sre','finops','api','evidence','audit','testing','chaos','quality','workload','latency','availability','cost','governance','compliance','observability','release','regression','provider','architecture','reliability','operations','risk','certification','global_research','account_identity','recurring_free','reset_window','independence','model_suitability','useful_units','context_lane','contract_drift','doc_freshness','credential_lifecycle','zero_spend','paid_fallback','monthly_governor','quota_exhaustion','single_point_failure','n_plus_two_recovery','economic_adversary','promotion_rollback','ceiling_adjudication']
ROLE_KEYS={r:['baseline_3m'] for r in ROLES}
for role,key in {'capacity':'stretch_10m','resilience':'n_plus_one_3m','billing':'zero_cost','security':'account_verified','quota':'reset_verified','failover':'n_plus_two_5m','finops':'zero_cost','evidence':'evidence_fresh','audit':'four_pools','chaos':'n_plus_two_5m','cost':'no_paid_fallback','governance':'recurring_free','compliance':'no_temporary_trial','provider':'four_pools','architecture':'four_pools','reliability':'n_plus_one_3m','risk':'n_plus_two_5m','certification':'stretch_10m','global_research':'evidence_refs','account_identity':'account_verified','recurring_free':'recurring_free','reset_window':'reset_verified','independence':'four_pools','useful_units':'positive_capacity','contract_drift':'evidence_fresh','doc_freshness':'evidence_fresh','credential_lifecycle':'account_verified','zero_spend':'zero_cost','paid_fallback':'no_paid_fallback','single_point_failure':'n_plus_one_3m','n_plus_two_recovery':'n_plus_two_5m','economic_adversary':'zero_cost','promotion_rollback':'evidence_refs','ceiling_adjudication':'stretch_10m'}.items():ROLE_KEYS[role]=list(dict.fromkeys(ROLE_KEYS[role]+[key]))
def audit(routes,evidence,now):
 r=certify_resilience(routes);c=chaos_floors(routes);pos=[x for x in routes if (_route_daily_units(x)[1] or 0)>0]
 checks={'baseline_3m':r['base_3m_status']=='PASS','growth_5m':r['growth_5m_status']=='PASS','stretch_10m':r['stretch_10m_status']=='PASS','n_plus_one_3m':c['n_plus_one_status']=='PASS','n_plus_two_3m':c['n_plus_two_status']=='PASS','n_plus_two_5m':c['n_plus_two_floor_useful_units_per_day']>=5_000_000,'four_pools':r['independent_pools']>=4,'evidence_fresh':bool(evidence) and all(evidence_freshness(x,now)['status']=='PASS' for x in evidence),'account_verified':all(x.get('account_verified') is True for x in pos),'recurring_free':all(x.get('recurring_free') is True for x in pos),'reset_verified':all(x.get('reset_verified') is True for x in pos),'zero_cost':all(x.get('mandatory_cost_usd',0)==0 for x in pos),'no_paid_fallback':all(x.get('no_paid_fallback') is True and x.get('paid_fallback_used',False) is False for x in pos),'no_temporary_trial':all(not x.get('temporary_trial',False) and not x.get('free_trial_expires_at') for x in pos),'evidence_refs':all(bool(x.get('evidence')) for x in pos),'positive_capacity':all((_route_daily_units(x)[1] or 0)>0 for x in pos)}
 hard=['baseline_3m','growth_5m','stretch_10m','n_plus_one_3m','n_plus_two_3m','n_plus_two_5m','four_pools','evidence_fresh','account_verified','recurring_free','reset_verified','zero_cost','no_paid_fallback','no_temporary_trial','evidence_refs']
 rr=[]
 for cycle in range(1,11):
  for role in ROLES:
   req=ROLE_KEYS[role];ok=all(checks.get(k,True) for k in req);rr.append({'cycle':cycle,'role':role,'status':'PASS' if ok else 'FAIL','failed':[k for k in req if not checks.get(k,True)]})
 findings=[k for k in hard if not checks[k]]
 return {'roles':50,'cycles':10,'checks':500,'status':'PASS' if not findings else 'FAIL','findings':findings,'passed_checks':sum(x['status']=='PASS' for x in rr),'failed_checks':sum(x['status']=='FAIL' for x in rr),'criteria':checks,'role_results':rr}
